<?php

namespace Container4JULiPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterProductQueryHandlerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the private 'EasyBell\Product\Application\Filter\FilterProductQueryHandler' shared autowired service.
     *
     * @return \EasyBell\Product\Application\Filter\FilterProductQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Shared/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Filter/FilterProductQueryHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Filter/ProductFilter.php';

        return $container->privates['EasyBell\\Product\\Application\\Filter\\FilterProductQueryHandler'] = new \EasyBell\Product\Application\Filter\FilterProductQueryHandler(new \EasyBell\Product\Application\Filter\ProductFilter(($container->privates['EasyBell\\Product\\Infrastructure\\Repository\\DoctrineProductRepository'] ?? $container->load('getDoctrineProductRepositoryService'))));
    }
}
