<?php

namespace Container4JULiPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostSpecialProductCommandHandlerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the private 'EasyBell\Product\Application\Create\PostSpecialProductCommandHandler' shared autowired service.
     *
     * @return \EasyBell\Product\Application\Create\PostSpecialProductCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Shared/Domain/Bus/Command/CommandHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Create/PostSpecialProductCommandHandler.php';

        return $container->privates['EasyBell\\Product\\Application\\Create\\PostSpecialProductCommandHandler'] = new \EasyBell\Product\Application\Create\PostSpecialProductCommandHandler(($container->privates['EasyBell\\Product\\Application\\Create\\ProductCreator'] ?? $container->load('getProductCreatorService')));
    }
}
