<?php

namespace Container4JULiPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductCreatorService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the private 'EasyBell\Product\Application\Create\ProductCreator' shared autowired service.
     *
     * @return \EasyBell\Product\Application\Create\ProductCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Create/ProductCreator.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Domain/PriceRule/PriceRuleFactory.php';

        return $container->privates['EasyBell\\Product\\Application\\Create\\ProductCreator'] = new \EasyBell\Product\Application\Create\ProductCreator(($container->privates['EasyBell\\Product\\Infrastructure\\Repository\\DoctrineProductRepository'] ?? $container->load('getDoctrineProductRepositoryService')), ($container->privates['EasyBell\\Shared\\Infrastructure\\Bus\\Event\\SymfonyInMemoryDomainEventBus'] ?? $container->load('getSymfonyInMemoryDomainEventBusService')), new \EasyBell\Product\Domain\PriceRule\PriceRuleFactory());
    }
}
