<?php

namespace Container4JULiPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductGetControllerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the public 'EasyBell\Apps\Product\Controller\ProductGetController' shared autowired service.
     *
     * @return \EasyBell\Apps\Product\Controller\ProductGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProductGetController.php';

        $container->services['EasyBell\\Apps\\Product\\Controller\\ProductGetController'] = $instance = new \EasyBell\Apps\Product\Controller\ProductGetController(($container->privates['EasyBell\\Shared\\Infrastructure\\Bus\\Query\\SymfonyInMemoryDomainQueryBus'] ?? $container->load('getSymfonyInMemoryDomainQueryBusService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('EasyBell\\Apps\\Product\\Controller\\ProductGetController', $container));

        return $instance;
    }
}
