<?php

namespace Container4JULiPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyInMemoryDomainEventBusService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the private 'EasyBell\Shared\Infrastructure\Bus\Event\SymfonyInMemoryDomainEventBus' shared autowired service.
     *
     * @return \EasyBell\Shared\Infrastructure\Bus\Event\SymfonyInMemoryDomainEventBus
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['EasyBell\\Shared\\Infrastructure\\Bus\\Event\\SymfonyInMemoryDomainEventBus'] = $container->createProxy('SymfonyInMemoryDomainEventBusGhost6fa5803', static fn () => \SymfonyInMemoryDomainEventBusGhost6fa5803::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        include_once \dirname(__DIR__, 6).'/src/Shared/Domain/Bus/Event/EventBus.php';
        include_once \dirname(__DIR__, 6).'/src/Shared/Infrastructure/Bus/Event/SymfonyInMemoryDomainEventBus.php';

        return ($lazyLoad->__construct(new RewindableGenerator(fn () => new \EmptyIterator(), 0)) && false ?: $lazyLoad);
    }
}
