<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXMlyU0p\EasyBell_Apps_Product_ProductKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXMlyU0p/EasyBell_Apps_Product_ProductKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXMlyU0p.legacy');

    return;
}

if (!\class_exists(EasyBell_Apps_Product_ProductKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXMlyU0p\EasyBell_Apps_Product_ProductKernelDevDebugContainer::class, EasyBell_Apps_Product_ProductKernelDevDebugContainer::class, false);
}

return new \ContainerXMlyU0p\EasyBell_Apps_Product_ProductKernelDevDebugContainer([
    'container.build_hash' => 'XMlyU0p',
    'container.build_id' => 'adf54861',
    'container.build_time' => 1717079285,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXMlyU0p');
