<?php

namespace ContainerXMlyU0p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityManagerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the public 'Doctrine\ORM\EntityManager' shared autowired service.
     *
     * @return \Doctrine\ORM\EntityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/persistence/src/Persistence/ObjectManager.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/orm/src/EntityManagerInterface.php';
        include_once \dirname(__DIR__, 6).'/vendor/doctrine/orm/src/EntityManager.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Infrastructure/Doctrine/ProductEntityManagerFactory.php';

        return $container->services['Doctrine\\ORM\\EntityManager'] = \EasyBell\Product\Infrastructure\Doctrine\ProductEntityManagerFactory::create(['driver' => $container->getEnv('PRODUCT_DATABASE_DRIVER'), 'host' => $container->getEnv('PRODUCT_DATABASE_HOST'), 'port' => $container->getEnv('PRODUCT_DATABASE_PORT'), 'dbname' => $container->getEnv('PRODUCT_DATABASE_NAME'), 'user' => $container->getEnv('PRODUCT_DATABASE_USER'), 'password' => $container->getEnv('PRODUCT_DATABASE_PASSWORD')], $container->getEnv('APP_ENV'));
    }
}
