<?php

namespace ContainerXMlyU0p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetProductQueryHandlerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the private 'EasyBell\Product\Application\Get\GetProductQueryHandler' shared autowired service.
     *
     * @return \EasyBell\Product\Application\Get\GetProductQueryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/src/Shared/Domain/Bus/Query/QueryHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Get/GetProductQueryHandler.php';
        include_once \dirname(__DIR__, 6).'/src/Product/Application/Get/ProductGetter.php';

        return $container->privates['EasyBell\\Product\\Application\\Get\\GetProductQueryHandler'] = new \EasyBell\Product\Application\Get\GetProductQueryHandler(new \EasyBell\Product\Application\Get\ProductGetter(($container->privates['EasyBell\\Product\\Infrastructure\\Repository\\DoctrineProductRepository'] ?? $container->load('getDoctrineProductRepositoryService'))));
    }
}
