<?php

namespace ContainerXMlyU0p;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductPostControllerService extends EasyBell_Apps_Product_ProductKernelDevDebugContainer
{
    /**
     * Gets the public 'EasyBell\Apps\Product\Controller\ProductPostController' shared autowired service.
     *
     * @return \EasyBell\Apps\Product\Controller\ProductPostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProductPostController.php';

        $container->services['EasyBell\\Apps\\Product\\Controller\\ProductPostController'] = $instance = new \EasyBell\Apps\Product\Controller\ProductPostController(($container->privates['EasyBell\\Shared\\Infrastructure\\Bus\\Command\\SymfonyInMemoryDomainCommandBus'] ?? $container->load('getSymfonyInMemoryDomainCommandBusService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('EasyBell\\Apps\\Product\\Controller\\ProductPostController', $container));

        return $instance;
    }
}
